pygments: true

# Set the title, tagline of the site
title: Tunisia - right to left treemap
tagline: Treemap and text is right-to-left

# Where is the template located (if it's not in the root)
# Remove the '#' from the next line and update the path if you have
# a subdirectory
subdirectory: '/tunisia'

# Set your Google Analytics Tracking Code
#ga_tracking_code: UA-8271754-8

# Where do you want to load openspendingjs from
openspendingjs: 'http://openspending.org/static/openspendingjs'

# Frontpage configurations
# We recommend you leave the openspending clause as is (or close to
# it as you can, e.g. you can replace "on this site" with
# "on [your site title]" or translate it.
frontpage:
    title: Tunisia right-to-left demo
    openspending: |-
        The data presented on this site comes from
        <a href="http://openspending.org">OpenSpending</a>, 
        where you can find information about 
        government finance from countries across the world.
